# general
log_freq: 20 
eval_freq: 5
epochs: 200
batch_size: 512
num_workers: 16
resume: logs/classifier/ckpt/ckpt_best_acc.pyth

# solver
base_lr: 0.0001

# data
val_path: /home/ubuntu/comp/data/extracted_features/26k/all.pkl

arch: fc_Classifier